### ISSUE TITLE
In all Referral mail Total amount is not correct

### ISSUE THREAD

**Issue by cedcoss-pooja** [MakeWebBetter/ultimate-woocommerce-points-and-rewards#21]
Bug name:referral amount mail is not correct send it will send sign in amount 
Area Path: frontend>my account page
Build Number:/Version Number 1.0.0
Status: New
Environment: LinuxMint 17.2/phpmyadmin
Description:Referral amount mail is not correct

**Comment by mohitmishra-cedcoss** [comment]
Fixed

**Comment by cedcoss-pooja** [comment]
![screenshot-mail google com-2019 10 10-19_37_25](https://user-images.githubusercontent.com/48902379/66576482-6c3b7080-eb95-11e9-81e7-d6758514d69a.png)
not fixed

**Comment by cedcoss-pooja** [comment]
done
