### ISSUE TITLE
"Points Log" is not displaying properly in under "Points Table"

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/ultimate-woocommerce-points-and-rewards#43]
"Points Log" is not displaying properly in under "Points Table"
![image](https://user-images.githubusercontent.com/25762796/64405171-e27f1b80-d09b-11e9-947b-ffb16cf3ab7b.png)

**Comment by mohitmishra-cedcoss** [comment]
Fixed

**Comment by anshucedcoss** [comment]
![image](https://user-images.githubusercontent.com/25762796/68190688-e1069c80-ffd3-11e9-9607-095f55dca123.png)

Still having the issue

**Comment by mohitmishra-cedcoss** [comment]
Fixed

**Comment by anshucedcoss** [comment]
DONE
